---
abstract: 'interface to the WHMCS billing and support system'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-WHMCS
requires:
  JSON: 0
  LWP::UserAgent: 0
  Moo: 0
resources:
  repository: git://github.com/fayland/perl-Net-WHMCS.git
version: 0.03
x_contributors:
  - 'Neil Bowers <neil@bowers.com>'
